apply plugin: 'com.android.library'

android {
    namespace 'com.analysys.compatibilitydemo'
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion

        ndk {
            abiFilters "armeabi-v7a", "x86_64", "x86", "arm64-v8a"
        }
        multiDexEnabled true
        manifestPlaceholders = Eval.me(ManifestPlaceholders)
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles('proguard-rules.pro')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    implementation 'com.getui:sdk:2.13.3.0'
    implementation 'cn.jiguang.sdk:jpush:3.1.8'
    implementation 'cn.jiguang.sdk:jcore:1.2.6'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.aliyun.ams:alicloud-android-push:3.4.0'
    implementation 'com.tencent.xinge:xinge:4.3.7-release'
    implementation 'com.tencent.jg:jg:1.1'
    implementation 'com.tencent.wup:wup:1.0.0.E-Release'
    implementation 'com.tencent.mid:mid:4.0.7-Release'

    api fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'

    if (apidemo_depend.toBoolean()) {
        implementation project(':analysys_core')
        implementation project(':analysys_push')
    } else {
        implementation 'cn.com.analysys:analysys-core:latest.release'
        implementation 'cn.com.analysys:analysys-push:latest.release'
    }
}
