apply from: "config.gradle"

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
    dependencies {
        apply from: "config.gradle"
        classpath 'com.android.tools.build:gradle:7.4.2'
        // ASM auto-track plugin; only needed when building apidemo with allgro enabled
        classpath 'cn.com.analysys:analysys-allgro-plugin:1.1.3'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'http://mvn.gt.igexin.com/nexus/content/repositories/releases/' }
    }
}
