apply plugin: 'groovy'
apply plugin: 'java-gradle-plugin'

group = 'cn.com.analysys'
version = '1.2.0'

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    compileOnly 'com.android.tools.build:gradle:7.4.2'

    implementation 'org.ow2.asm:asm:9.2'
    implementation 'org.ow2.asm:asm-commons:9.2'
    implementation 'org.ow2.asm:asm-analysis:9.2'
    implementation 'org.ow2.asm:asm-util:9.2'
    implementation 'org.ow2.asm:asm-tree:9.2'
}

repositories {
    google()
    mavenCentral()
}

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

gradlePlugin {
    plugins {
        analysysAndroidPlugin {
            id = 'com.analysys.android.plugin'
            implementationClass = 'com.analysys.plugin.AnalysysPlugin'
        }
    }
}
