plugins {
    id 'com.analysys.android.plugin' apply false
}

if (apidemo_type.toBoolean()) {
    apply plugin: 'com.android.application'
    apply plugin: 'com.analysys.android.plugin'
} else {
    apply plugin: 'com.android.library'
}

android {
    namespace 'com.analysys.apidemo'
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        buildConfigField("String", "Build_Type", "\"${Build_Type}\"")

        if (apidemo_type.toBoolean()) {
            applicationId "com.analysys.demo"
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = Eval.me(ManifestPlaceholders)
    }

    if (apidemo_type.toBoolean()) {
        signingConfigs {
            release {
                keyAlias 'apidemo'
                keyPassword '123456'
                storeFile file('apidemo')
                storePassword '123456'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles('proguard-rules.pro')
            if (apidemo_type.toBoolean()) {
                signingConfig signingConfigs.release
            }
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
        disable 'UnusedResources', 'RestrictedApi'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        dataBinding true
    }
}

dependencies {
    if (apidemo_depend.toBoolean()) {
        api project(':analysys_arkanalysys')
    } else {
        api 'cn.com.analysys:analysys-arkanalysys:latest.release'
    }
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.fragment:fragment:1.6.1'
    compileOnly 'androidx.recyclerview:recyclerview:1.1.0'
}

tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('charSet', 'UTF-8')
}
